USE bookstore;

CREATE TABLE DANHMUC(
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  tenDanhMuc VARCHAR(255) NOT NULL,
  ngayTao TIMESTAMP NULL,
  ngaySua TIMESTAMP NULL,
  nguoiTao VARCHAR(255) NULL,
  nguoiSua VARCHAR(255) NULL
);

CREATE TABLE TAIKHOAN (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  tenTaiKhoan VARCHAR(150) NOT NULL,
  matKhau VARCHAR(150) NOT NULL,
  ngayTao TIMESTAMP NULL,
  ngaySua TIMESTAMP NULL,
  nguoiTao VARCHAR(255) NULL,
  nguoiSua VARCHAR(255) NULL
);

CREATE TABLE NGUOIDUNG (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  tenNguoiDung VARCHAR(255),
  sdt VARCHAR(255),
  diaChi VARCHAR(255),
  chucVu INT,
  ngayTao TIMESTAMP NULL,
  ngaySua TIMESTAMP NULL,
  nguoiTao VARCHAR(255) NULL,
  nguoiSua VARCHAR(255) NULL
);

CREATE TABLE THANHTOAN (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  phuongThucThanhToan VARCHAR(255) NOT NULL,
  ngayTao TIMESTAMP NULL,
  ngaySua TIMESTAMP NULL,
  nguoiTao VARCHAR(255) NULL,
  nguoiSua VARCHAR(255) NULL
);

CREATE TABLE DONHANG (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  tinhTrang VARCHAR(255) NOT NULL,
  diaChiNhanHang VARCHAR(255),
  tongTien DOUBLE,
  
  id_nguoiDung INT NOT NULL,
  id_thanhToan INT NOT NULL,
  
  ngayTao TIMESTAMP NULL,
  ngaySua TIMESTAMP NULL,
  nguoiTao VARCHAR(255) NULL,
  nguoiSua VARCHAR(255) NULL
);

ALTER TABLE DONHANG ADD CONSTRAINT fk_DONHANG_NGUOIDUNG FOREIGN KEY (id_nguoiDung) REFERENCES NGUOIDUNG(id);
ALTER TABLE DONHANG ADD CONSTRAINT fk_DONHANG_THANHTOAN FOREIGN KEY (id_thanhToan) REFERENCES THANHTOAN(id);

CREATE TABLE CHITIETDONHANG (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  maSach INT NOT NULL,
  soLuong INT NOT NULL,
  
  id_donHang INT NOT NULL,
  
  ngayTao TIMESTAMP NULL,
  ngaySua TIMESTAMP NULL,
  nguoiTao VARCHAR(255) NULL,
  nguoiSua VARCHAR(255) NULL
);

ALTER TABLE CHITIETDONHANG ADD CONSTRAINT fk_CHITIETDONHANG_DONHANG FOREIGN KEY (id_donHang) REFERENCES DONHANG(id);

CREATE TABLE SACH (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  tenSach VARCHAR(255),
  anhMinhHoa VARCHAR(255),
  donGia DOUBLE,
  tinhTrang INT,
  nhaCungCap VARCHAR(255),
  hinhThucBia VARCHAR(255),
  
  id_chiTietDonHang INT NOT NULL,
  id_danhMuc INT NOT NULL,
  
  ngayTao TIMESTAMP NULL,
  ngaySua TIMESTAMP NULL,
  nguoiTao VARCHAR(255) NULL,
  nguoiSua VARCHAR(255) NULL
);

ALTER TABLE SACH ADD CONSTRAINT fk_SACH_CHITIETDONHANG FOREIGN KEY (id_chiTietDonHang) REFERENCES CHITIETDONHANG(id);
ALTER TABLE SACH ADD CONSTRAINT fk_SACH_DANHMUC FOREIGN KEY (id_danhMuc) REFERENCES DANHMUC(id);

CREATE TABLE TACGIA (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  tenTacGia VARCHAR(255),
  anhMinhHoa VARCHAR(255),  
  ngayTao TIMESTAMP NULL,
  ngaySua TIMESTAMP NULL,
  nguoiTao VARCHAR(255) NULL,
  nguoiSua VARCHAR(255) NULL
);

CREATE TABLE TACGIA_SACH (
  id_tacGia INT NOT NULL,
  id_sach INT NOT NULL,
  PRIMARY KEY(id_tacGia, id_sach),
  
  ngayTao TIMESTAMP NULL,
  ngaySua TIMESTAMP NULL,
  nguoiTao VARCHAR(255) NULL,
  nguoiSua VARCHAR(255) NULL
);

ALTER TABLE TACGIA_SACH ADD CONSTRAINT fk_TACGIA_SACH_TACGIA FOREIGN KEY (id_tacGia) REFERENCES TACGIA(id);
ALTER TABLE TACGIA_SACH ADD CONSTRAINT fk_TACGIA_SACH_SACH FOREIGN KEY (id_sach) REFERENCES SACH(id);
